---
apiVersion: v1
kind: Secret
metadata:
  name: eloy83-eloy83-poi-map-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus2/eloy83-frontend-gitops
